### ISSUE TITLE
Setup is missing package "regex"

### ISSUE THREAD

**Issue by Danamir** [carefree0910/carefree-drawboard#3]
**Describe the bug**
When launching the first time, a message error appears : 

```
    import regex as re
ModuleNotFoundError: No module named 'regex'
```

**To Reproduce**
1. install via git clone and `pip install -e .`, or `pip install carefree-drawboard`
2. launch any `cfdraw` command line (i.e init, run ...)
3. See error

**Solution**
Simply install `regex`, or add it to `setup.py` .

```
pip install regex
```

**Comment by carefree0910** [comment]
Oh, nice catch! I'll add `regex` to my dependency then, thanks for your feedback!!
